(ns clj-simple-form.mock-html-ns)

(defn check-box [& args] "<check-box />")
(defn drop-down [& args] "<drop-down />")
(defn email-field [& args] "<email-field />")
(defn error [& args] "<error />")
(defn file-upload [& args] "<file-upload />")
(defn group-check-box [& args] "<group-check-box />")
(defn group-radio-button [& args] "<email-field />")
(defn hint [& args] "<hint />")
(defn label [& args] "<label />")
(defn password-field [& args] "<password-field />")
(defn text-area [& args] "<text-area />")
(defn text-field [& args] "<text-field />")
(defn wrapper [& args] "<wrapper />")
